[[constraint]]
  branch = "master"
  name = "k8s.io/api"

[[constraint]]
  name = "k8s.io/client-go"
  version = "12.0.0"

[[constraint]]
  name = "k8s.io/klog"
  version = "0.3.3"

[prune]
  go-tests = true
  unused-packages = true
