version: 2.1

jobs:
  build:
    working_directory: /home/circleci/go/src/github.com/patoarvizu/cloudflare-route53-controller
    docker:
      - image: docker:18.09-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push image
          command: |
            apk add curl gnupg
            curl -L https://github.com/theupdateframework/notary/releases/download/v0.6.1/notary-Linux-amd64 -o notary
            chmod +x notary
            mv notary /usr/local/bin
            echo $ENCODED_NOTARY_ROLE_KEY | base64 -d > cloudflare-route53-operator-circleci.key
            export NOTARY_DELEGATION_PASSPHRASE=$NOTARY_ROLE_PASSPHRASE
            notary -s https://notary.docker.io -d ~/.docker/trust key import cloudflare-route53-operator-circleci.key --role cloudflare-route53-operator-circleci
            export DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE=$NOTARY_DELEGATION_PASSPHRASE
            echo $DOCKER_HUB_KEY | docker login -u $DOCKER_HUB_USER --password-stdin
            DOCKER_BUILD_ARGS="--build-arg GIT_COMMIT=$CIRCLE_SHA1 --build-arg GIT_TAG=$CIRCLE_TAG --build-arg COMMIT_TIMESTAMP=$(git log -1 --format=%at) --build-arg AUTHOR_EMAIL=$(git log -1 --format=%ae) --build-arg SIGNATURE_KEY=$(git log -1 --format=%GK)"
            docker build -f docker/Dockerfile -t patoarvizu/cloudflare-route53-controller:$CIRCLE_SHA1 $DOCKER_BUILD_ARGS .
            export DOCKER_CONTENT_TRUST=1
            VERSION=${CIRCLE_TAG:-latest}
            docker tag patoarvizu/cloudflare-route53-controller:$CIRCLE_SHA1 patoarvizu/cloudflare-route53-controller:latest
            docker tag patoarvizu/cloudflare-route53-controller:$CIRCLE_SHA1 patoarvizu/cloudflare-route53-controller:$VERSION
            docker push patoarvizu/cloudflare-route53-controller:$CIRCLE_SHA1
            docker push patoarvizu/cloudflare-route53-controller:$VERSION
            docker push patoarvizu/cloudflare-route53-controller:latest

workflows:
  version: 2
  build-controller:
    jobs:
      - build:
          filters:
            tags:
              only: /^v\d+\.\d+.\d+$/